ъspring:
  datasource:
    url: jdbc:postgresql://localhost:5434/book_store
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

jwt:
  secret: my-super-secret-key-for-book-store-project
  expiration: 86400000